### ISSUE TITLE
Increase padding between SingleVehicleStats content and line decoration

### ISSUE THREAD

**Issue by murtoM** [murtoM/lopokulu-react#23]
The padding highlighted in red in the screenshot could be larger, maybe 1em - experiment what looks good.

![image](https://user-images.githubusercontent.com/14340484/145709331-7c090a70-841c-4326-b62c-d999a3338350.png)

**Comment by murtoM** [comment]
Someone else can do it as well, if they want.

**Comment by JaniLeht** [comment]
Good issue. It will be look better with more padding

**Comment by mtijas** [comment]
Also left margins do not match the rest of the app (compare between these and left margin of header [_(DEF-567)_]).

**Comment by murtoM** [comment]
> Also left margins do not match the rest of the app (compare between these and left margin of header [_(DEF-567)_]).

This could be a new issue.
